
<div id="page-actions">
    <?php echo $this->hyperlink('Add new thesaurus', $this->url('admin/thesauri/add'), ['class' => 'button']); ?>
</div>

<h1>Thesauri</h1>


<?php foreach ($thesauri as $thesaurus): ?>
    <div class="thesaurus">
        <h4>

            <span class="edit-link">
                <a href="#"
                        data-sidebar-content-url="thesauri/delete-confirm/<?php echo $thesaurus['id'] ?>"
                        class="o-icon-delete sidebar-content"
                        aria-label="Delete"
                        title="Delete"></a>
            </span>

            <span class="edit-link">
                <a class='o-icon-edit' href='<?php echo $thesaurus['edit_link'] ?>'></a>
            </span>

            <?php echo $thesaurus['label'] ?> 
            [<a href="<?php echo $thesaurus["link"] ?>" ><?php echo $thesaurus["count"] ?></a>]
            <a href="#" class="toggleConceptList">⇣</a>
        </h4>


        <div class="conceptList" style="display:none;">
        <?php foreach($thesaurus['items'] as $item): ?>
        <div class="concept">
            <span class="edit-link">
                <a class='o-icon-edit' href='<?php echo $item->url('edit') ?>'></a>
            </span>
            <?php echo $item->displayTitle()  ?>
        </div>
        <?php endforeach; ?>
            <div class="concept">
                <a class="o-icon-add" href="thesauri/create-concept/<?php echo $thesaurus['id'] ?>"></a>
            </div>        
        </div>
    
    </div>
<?php endforeach; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="Close"
        title="Close"></a>
    <div class="sidebar-content"></div>
</div>

<script>
    $('.toggleConceptList').click(function(e) {
        e.preventDefault()

        const list = e.currentTarget.parentElement.nextElementSibling
        if (list.style.display === "none") {
            list.style.display = "block"
            e.currentTarget.innerHTML = "⇡"
        } else {
            list.style.display = "none"
            e.currentTarget.innerHTML = "⇣"
        }        
    })
</script>

<style>
    .concept {
        margin-top:0.4em;
    }
    .thesaurus {
        margin-top: 1em;
    }
    .conceptList {
        margin-left:1em;
        display: none;
    }
    .edit-link {
        margin-right: 0.5em;
    }
</style>